PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/vndk-34/lib64/libevent.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libevent.so \
    $(LOCAL_PATH)/vndk-34/lib64/libcrypto.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libcrypto.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hardware.graphics.common@1.1.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hardware.graphics.common@1.1.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hardware.graphics.composer3-V1-ndk.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hardware.graphics.composer3-V1-ndk.so \
    $(LOCAL_PATH)/vndk-34/lib64/libsysutils.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libsysutils.so \
    $(LOCAL_PATH)/vndk-34/lib64/libprocessgroup.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libprocessgroup.so \
    $(LOCAL_PATH)/vndk-34/lib64/libstagefright_omx.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libstagefright_omx.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hardware.graphics.bufferqueue@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hardware.graphics.bufferqueue@1.0.so \
    $(LOCAL_PATH)/vndk-34/lib64/libbinder.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libbinder.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hardware.graphics.common-V4-ndk.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hardware.graphics.common-V4-ndk.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hardware.media@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hardware.media@1.0.so \
    $(LOCAL_PATH)/vndk-34/lib64/libc++.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libc++.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hardware.graphics.common@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hardware.graphics.common@1.0.so \
    $(LOCAL_PATH)/vndk-34/lib64/libcutils.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libcutils.so \
    $(LOCAL_PATH)/vndk-34/lib64/libcrypto_utils.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libcrypto_utils.so \
    $(LOCAL_PATH)/vndk-34/lib64/libcompiler_rt.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libcompiler_rt.so \
    $(LOCAL_PATH)/vndk-34/lib64/libstagefright_bufferqueue_helper.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libstagefright_bufferqueue_helper.so \
    $(LOCAL_PATH)/vndk-34/lib64/libmedia_helper.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libmedia_helper.so \
    $(LOCAL_PATH)/vndk-34/lib64/libhidlallocatorutils.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libhidlallocatorutils.so \
    $(LOCAL_PATH)/vndk-34/lib64/libcap.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libcap.so \
    $(LOCAL_PATH)/vndk-34/lib64/libyuv.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libyuv.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hardware.graphics.allocator@2.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hardware.graphics.allocator@2.0.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hardware.confirmationui-support-lib.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hardware.confirmationui-support-lib.so \
    $(LOCAL_PATH)/vndk-34/lib64/libhardware.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libhardware.so \
    $(LOCAL_PATH)/vndk-34/lib64/libblas.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libblas.so \
    $(LOCAL_PATH)/vndk-34/lib64/libaudioroute.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libaudioroute.so \
    $(LOCAL_PATH)/vndk-34/lib64/libhidlbase.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libhidlbase.so \
    $(LOCAL_PATH)/vndk-34/lib64/liblzma.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/liblzma.so \
    $(LOCAL_PATH)/vndk-34/lib64/libpower.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libpower.so \
    $(LOCAL_PATH)/vndk-34/lib64/libstagefright_bufferpool@2.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libstagefright_bufferpool@2.0.so \
    $(LOCAL_PATH)/vndk-34/lib64/libhardware_legacy.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libhardware_legacy.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hardware.configstore@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hardware.configstore@1.0.so \
    $(LOCAL_PATH)/vndk-34/lib64/libbcinfo.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libbcinfo.so \
    $(LOCAL_PATH)/vndk-34/lib64/libgralloctypes.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libgralloctypes.so \
    $(LOCAL_PATH)/vndk-34/lib64/libpng.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libpng.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.frameworks.cameraservice.device-V1-ndk.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.frameworks.cameraservice.device-V1-ndk.so \
    $(LOCAL_PATH)/vndk-34/lib64/libutils.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libutils.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hardware.configstore@1.1.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hardware.configstore@1.1.so \
    $(LOCAL_PATH)/vndk-34/lib64/libminijail.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libminijail.so \
    $(LOCAL_PATH)/vndk-34/lib64/libpiex.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libpiex.so \
    $(LOCAL_PATH)/vndk-34/lib64/liblz4.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/liblz4.so \
    $(LOCAL_PATH)/vndk-34/lib64/libclang_rt.ubsan_standalone-aarch64-android.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libclang_rt.ubsan_standalone-aarch64-android.so \
    $(LOCAL_PATH)/vndk-34/lib64/libradio_metadata.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libradio_metadata.so \
    $(LOCAL_PATH)/vndk-34/lib64/libhidlmemory.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libhidlmemory.so \
    $(LOCAL_PATH)/vndk-34/lib64/libui.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libui.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hardware.media.bufferpool@2.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hardware.media.bufferpool@2.0.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hardware.soundtrigger@2.0-core.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hardware.soundtrigger@2.0-core.so \
    $(LOCAL_PATH)/vndk-34/lib64/libprocinfo.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libprocinfo.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.system.suspend@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.system.suspend@1.0.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hidl.safe_union@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hidl.safe_union@1.0.so \
    $(LOCAL_PATH)/vndk-34/lib64/libcodec2.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libcodec2.so \
    $(LOCAL_PATH)/vndk-34/lib64/libwifi-system-iface.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libwifi-system-iface.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hardware.graphics.mapper@3.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hardware.graphics.mapper@3.0.so \
    $(LOCAL_PATH)/vndk-34/lib64/libdumpstateutil.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libdumpstateutil.so \
    $(LOCAL_PATH)/vndk-34/lib64/libldacBT_abr.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libldacBT_abr.so \
    $(LOCAL_PATH)/vndk-34/lib64/libstagefright_omx_utils.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libstagefright_omx_utils.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hardware.renderscript@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hardware.renderscript@1.0.so \
    $(LOCAL_PATH)/vndk-34/lib64/libspeexresampler.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libspeexresampler.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hardware.graphics.allocator@4.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hardware.graphics.allocator@4.0.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hardware.graphics.allocator@3.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hardware.graphics.allocator@3.0.so \
    $(LOCAL_PATH)/vndk-34/lib64/libtinyxml2.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libtinyxml2.so \
    $(LOCAL_PATH)/vndk-34/lib64/libdiskconfig.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libdiskconfig.so \
    $(LOCAL_PATH)/vndk-34/lib64/libRSDriver.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libRSDriver.so \
    $(LOCAL_PATH)/vndk-34/lib64/libexpat.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libexpat.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hardware.graphics.mapper@2.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hardware.graphics.mapper@2.0.so \
    $(LOCAL_PATH)/vndk-34/lib64/libxml2.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libxml2.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hardware.memtrack@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hardware.memtrack@1.0.so \
    $(LOCAL_PATH)/vndk-34/lib64/libnetutils.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libnetutils.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hidl.memory@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hidl.memory@1.0.so \
    $(LOCAL_PATH)/vndk-34/lib64/libmkbootimg_abi_check.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libmkbootimg_abi_check.so \
    $(LOCAL_PATH)/vndk-34/lib64/libssl.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libssl.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hardware.graphics.bufferqueue@2.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hardware.graphics.bufferqueue@2.0.so \
    $(LOCAL_PATH)/vndk-34/lib64/libstagefright_foundation.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libstagefright_foundation.so \
    $(LOCAL_PATH)/vndk-34/lib64/libmemtrack.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libmemtrack.so \
    $(LOCAL_PATH)/vndk-34/lib64/libRSCpuRef.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libRSCpuRef.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hardware.common.fmq-V1-ndk.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hardware.common.fmq-V1-ndk.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hidl.token@1.0-utils.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hidl.token@1.0-utils.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hardware.graphics.mapper@2.1.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hardware.graphics.mapper@2.1.so \
    $(LOCAL_PATH)/vndk-34/lib64/libjpeg.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libjpeg.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hardware.memtrack-V1-ndk.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hardware.memtrack-V1-ndk.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.frameworks.cameraservice.service-V1-ndk.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.frameworks.cameraservice.service-V1-ndk.so \
    $(LOCAL_PATH)/vndk-34/lib64/libpcre2.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libpcre2.so \
    $(LOCAL_PATH)/vndk-34/lib64/libdmabufheap.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libdmabufheap.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.system.suspend-V1-ndk.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.system.suspend-V1-ndk.so \
    $(LOCAL_PATH)/vndk-34/lib64/libfmq.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libfmq.so \
    $(LOCAL_PATH)/vndk-34/lib64/libgui.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libgui.so \
    $(LOCAL_PATH)/vndk-34/lib64/libusbhost.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libusbhost.so \
    $(LOCAL_PATH)/vndk-34/lib64/libbase.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libbase.so \
    $(LOCAL_PATH)/vndk-34/lib64/libcamera_metadata.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libcamera_metadata.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hardware.audio.common@2.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hardware.audio.common@2.0.so \
    $(LOCAL_PATH)/vndk-34/lib64/libsqlite.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libsqlite.so \
    $(LOCAL_PATH)/vndk-34/lib64/libion.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libion.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hardware.graphics.mapper@4.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hardware.graphics.mapper@4.0.so \
    $(LOCAL_PATH)/vndk-34/lib64/libziparchive.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libziparchive.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hardware.soundtrigger@2.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hardware.soundtrigger@2.0.so \
    $(LOCAL_PATH)/vndk-34/lib64/libbufferqueueconverter.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libbufferqueueconverter.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hardware.graphics.common@1.2.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hardware.graphics.common@1.2.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hidl.token@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hidl.token@1.0.so \
    $(LOCAL_PATH)/vndk-34/lib64/libnl.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libnl.so \
    $(LOCAL_PATH)/vndk-34/lib64/libmedia_omx.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libmedia_omx.so \
    $(LOCAL_PATH)/vndk-34/lib64/libz.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libz.so \
    $(LOCAL_PATH)/vndk-34/lib64/libtinyalsa.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libtinyalsa.so \
    $(LOCAL_PATH)/vndk-34/lib64/libcurl.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libcurl.so \
    $(LOCAL_PATH)/vndk-34/lib64/libstagefright_xmlparser.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libstagefright_xmlparser.so \
    $(LOCAL_PATH)/vndk-34/lib64/libgatekeeper.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libgatekeeper.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hardware.graphics.allocator-V2-ndk.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hardware.graphics.allocator-V2-ndk.so \
    $(LOCAL_PATH)/vndk-34/lib64/libjsoncpp.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libjsoncpp.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hardware.configstore-utils.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hardware.configstore-utils.so \
    $(LOCAL_PATH)/vndk-34/lib64/libaudioutils.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libaudioutils.so \
    $(LOCAL_PATH)/vndk-34/lib64/libcn-cbor.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libcn-cbor.so \
    $(LOCAL_PATH)/vndk-34/lib64/libRS_internal.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libRS_internal.so \
    $(LOCAL_PATH)/vndk-34/lib64/libexif.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libexif.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.frameworks.cameraservice.common-V1-ndk.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.frameworks.cameraservice.common-V1-ndk.so \
    $(LOCAL_PATH)/vndk-34/lib64/libutilscallstack.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libutilscallstack.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hardware.media.omx@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hardware.media.omx@1.0.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hardware.common-V2-ndk.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hardware.common-V2-ndk.so \
    $(LOCAL_PATH)/vndk-34/lib64/libldacBT_enc.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libldacBT_enc.so \
    $(LOCAL_PATH)/vndk-34/lib64/libunwindstack.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/libunwindstack.so \
    $(LOCAL_PATH)/vndk-34/lib64/android.hidl.memory.token@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/android.hidl.memory.token@1.0.so \
    $(LOCAL_PATH)/vndk-34/lib64/hw/android.hidl.memory@1.0-impl.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vndk-34/hw \
    $(LOCAL_PATH)/vndk-34/lib/libevent.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libevent.so \
    $(LOCAL_PATH)/vndk-34/lib/libcrypto.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libcrypto.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hardware.graphics.common@1.1.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hardware.graphics.common@1.1.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hardware.graphics.composer3-V1-ndk.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hardware.graphics.composer3-V1-ndk.so \
    $(LOCAL_PATH)/vndk-34/lib/libsysutils.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libsysutils.so \
    $(LOCAL_PATH)/vndk-34/lib/libprocessgroup.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libprocessgroup.so \
    $(LOCAL_PATH)/vndk-34/lib/libstagefright_omx.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libstagefright_omx.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hardware.graphics.bufferqueue@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hardware.graphics.bufferqueue@1.0.so \
    $(LOCAL_PATH)/vndk-34/lib/libbinder.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libbinder.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hardware.graphics.common-V4-ndk.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hardware.graphics.common-V4-ndk.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hardware.media@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hardware.media@1.0.so \
    $(LOCAL_PATH)/vndk-34/lib/libc++.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libc++.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hardware.graphics.common@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hardware.graphics.common@1.0.so \
    $(LOCAL_PATH)/vndk-34/lib/libcutils.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libcutils.so \
    $(LOCAL_PATH)/vndk-34/lib/libcrypto_utils.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libcrypto_utils.so \
    $(LOCAL_PATH)/vndk-34/lib/libcompiler_rt.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libcompiler_rt.so \
    $(LOCAL_PATH)/vndk-34/lib/libstagefright_bufferqueue_helper.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libstagefright_bufferqueue_helper.so \
    $(LOCAL_PATH)/vndk-34/lib/libmedia_helper.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libmedia_helper.so \
    $(LOCAL_PATH)/vndk-34/lib/libhidlallocatorutils.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libhidlallocatorutils.so \
    $(LOCAL_PATH)/vndk-34/lib/libcap.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libcap.so \
    $(LOCAL_PATH)/vndk-34/lib/libyuv.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libyuv.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hardware.graphics.allocator@2.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hardware.graphics.allocator@2.0.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hardware.confirmationui-support-lib.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hardware.confirmationui-support-lib.so \
    $(LOCAL_PATH)/vndk-34/lib/libhardware.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libhardware.so \
    $(LOCAL_PATH)/vndk-34/lib/libblas.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libblas.so \
    $(LOCAL_PATH)/vndk-34/lib/libaudioroute.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libaudioroute.so \
    $(LOCAL_PATH)/vndk-34/lib/libhidlbase.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libhidlbase.so \
    $(LOCAL_PATH)/vndk-34/lib/liblzma.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/liblzma.so \
    $(LOCAL_PATH)/vndk-34/lib/libpower.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libpower.so \
    $(LOCAL_PATH)/vndk-34/lib/libstagefright_bufferpool@2.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libstagefright_bufferpool@2.0.so \
    $(LOCAL_PATH)/vndk-34/lib/libhardware_legacy.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libhardware_legacy.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hardware.configstore@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hardware.configstore@1.0.so \
    $(LOCAL_PATH)/vndk-34/lib/libbcinfo.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libbcinfo.so \
    $(LOCAL_PATH)/vndk-34/lib/libgralloctypes.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libgralloctypes.so \
    $(LOCAL_PATH)/vndk-34/lib/libpng.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libpng.so \
    $(LOCAL_PATH)/vndk-34/lib/android.frameworks.cameraservice.device-V1-ndk.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.frameworks.cameraservice.device-V1-ndk.so \
    $(LOCAL_PATH)/vndk-34/lib/libutils.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libutils.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hardware.configstore@1.1.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hardware.configstore@1.1.so \
    $(LOCAL_PATH)/vndk-34/lib/libminijail.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libminijail.so \
    $(LOCAL_PATH)/vndk-34/lib/libpiex.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libpiex.so \
    $(LOCAL_PATH)/vndk-34/lib/liblz4.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/liblz4.so \
    $(LOCAL_PATH)/vndk-34/lib/libradio_metadata.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libradio_metadata.so \
    $(LOCAL_PATH)/vndk-34/lib/libhidlmemory.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libhidlmemory.so \
    $(LOCAL_PATH)/vndk-34/lib/libui.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libui.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hardware.media.bufferpool@2.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hardware.media.bufferpool@2.0.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hardware.soundtrigger@2.0-core.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hardware.soundtrigger@2.0-core.so \
    $(LOCAL_PATH)/vndk-34/lib/libprocinfo.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libprocinfo.so \
    $(LOCAL_PATH)/vndk-34/lib/android.system.suspend@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.system.suspend@1.0.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hidl.safe_union@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hidl.safe_union@1.0.so \
    $(LOCAL_PATH)/vndk-34/lib/libcodec2.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libcodec2.so \
    $(LOCAL_PATH)/vndk-34/lib/libwifi-system-iface.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libwifi-system-iface.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hardware.graphics.mapper@3.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hardware.graphics.mapper@3.0.so \
    $(LOCAL_PATH)/vndk-34/lib/libdumpstateutil.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libdumpstateutil.so \
    $(LOCAL_PATH)/vndk-34/lib/libldacBT_abr.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libldacBT_abr.so \
    $(LOCAL_PATH)/vndk-34/lib/libstagefright_omx_utils.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libstagefright_omx_utils.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hardware.renderscript@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hardware.renderscript@1.0.so \
    $(LOCAL_PATH)/vndk-34/lib/libclang_rt.ubsan_standalone-arm-android.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libclang_rt.ubsan_standalone-arm-android.so \
    $(LOCAL_PATH)/vndk-34/lib/libspeexresampler.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libspeexresampler.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hardware.graphics.allocator@4.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hardware.graphics.allocator@4.0.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hardware.graphics.allocator@3.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hardware.graphics.allocator@3.0.so \
    $(LOCAL_PATH)/vndk-34/lib/libtinyxml2.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libtinyxml2.so \
    $(LOCAL_PATH)/vndk-34/lib/libdiskconfig.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libdiskconfig.so \
    $(LOCAL_PATH)/vndk-34/lib/libRSDriver.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libRSDriver.so \
    $(LOCAL_PATH)/vndk-34/lib/libexpat.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libexpat.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hardware.graphics.mapper@2.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hardware.graphics.mapper@2.0.so \
    $(LOCAL_PATH)/vndk-34/lib/libxml2.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libxml2.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hardware.memtrack@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hardware.memtrack@1.0.so \
    $(LOCAL_PATH)/vndk-34/lib/libnetutils.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libnetutils.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hidl.memory@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hidl.memory@1.0.so \
    $(LOCAL_PATH)/vndk-34/lib/libmkbootimg_abi_check.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libmkbootimg_abi_check.so \
    $(LOCAL_PATH)/vndk-34/lib/libssl.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libssl.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hardware.graphics.bufferqueue@2.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hardware.graphics.bufferqueue@2.0.so \
    $(LOCAL_PATH)/vndk-34/lib/libstagefright_foundation.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libstagefright_foundation.so \
    $(LOCAL_PATH)/vndk-34/lib/libmemtrack.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libmemtrack.so \
    $(LOCAL_PATH)/vndk-34/lib/libRSCpuRef.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libRSCpuRef.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hardware.common.fmq-V1-ndk.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hardware.common.fmq-V1-ndk.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hidl.token@1.0-utils.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hidl.token@1.0-utils.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hardware.graphics.mapper@2.1.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hardware.graphics.mapper@2.1.so \
    $(LOCAL_PATH)/vndk-34/lib/libjpeg.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libjpeg.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hardware.memtrack-V1-ndk.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hardware.memtrack-V1-ndk.so \
    $(LOCAL_PATH)/vndk-34/lib/android.frameworks.cameraservice.service-V1-ndk.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.frameworks.cameraservice.service-V1-ndk.so \
    $(LOCAL_PATH)/vndk-34/lib/libpcre2.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libpcre2.so \
    $(LOCAL_PATH)/vndk-34/lib/libdmabufheap.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libdmabufheap.so \
    $(LOCAL_PATH)/vndk-34/lib/android.system.suspend-V1-ndk.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.system.suspend-V1-ndk.so \
    $(LOCAL_PATH)/vndk-34/lib/libfmq.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libfmq.so \
    $(LOCAL_PATH)/vndk-34/lib/libgui.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libgui.so \
    $(LOCAL_PATH)/vndk-34/lib/libusbhost.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libusbhost.so \
    $(LOCAL_PATH)/vndk-34/lib/libbase.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libbase.so \
    $(LOCAL_PATH)/vndk-34/lib/libcamera_metadata.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libcamera_metadata.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hardware.audio.common@2.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hardware.audio.common@2.0.so \
    $(LOCAL_PATH)/vndk-34/lib/libsqlite.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libsqlite.so \
    $(LOCAL_PATH)/vndk-34/lib/libion.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libion.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hardware.graphics.mapper@4.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hardware.graphics.mapper@4.0.so \
    $(LOCAL_PATH)/vndk-34/lib/libziparchive.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libziparchive.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hardware.soundtrigger@2.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hardware.soundtrigger@2.0.so \
    $(LOCAL_PATH)/vndk-34/lib/libbufferqueueconverter.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libbufferqueueconverter.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hardware.graphics.common@1.2.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hardware.graphics.common@1.2.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hidl.token@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hidl.token@1.0.so \
    $(LOCAL_PATH)/vndk-34/lib/libnl.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libnl.so \
    $(LOCAL_PATH)/vndk-34/lib/libmedia_omx.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libmedia_omx.so \
    $(LOCAL_PATH)/vndk-34/lib/libz.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libz.so \
    $(LOCAL_PATH)/vndk-34/lib/libtinyalsa.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libtinyalsa.so \
    $(LOCAL_PATH)/vndk-34/lib/libcurl.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libcurl.so \
    $(LOCAL_PATH)/vndk-34/lib/libstagefright_xmlparser.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libstagefright_xmlparser.so \
    $(LOCAL_PATH)/vndk-34/lib/libgatekeeper.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libgatekeeper.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hardware.graphics.allocator-V2-ndk.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hardware.graphics.allocator-V2-ndk.so \
    $(LOCAL_PATH)/vndk-34/lib/libjsoncpp.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libjsoncpp.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hardware.configstore-utils.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hardware.configstore-utils.so \
    $(LOCAL_PATH)/vndk-34/lib/libaudioutils.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libaudioutils.so \
    $(LOCAL_PATH)/vndk-34/lib/libcn-cbor.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libcn-cbor.so \
    $(LOCAL_PATH)/vndk-34/lib/libRS_internal.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libRS_internal.so \
    $(LOCAL_PATH)/vndk-34/lib/libexif.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libexif.so \
    $(LOCAL_PATH)/vndk-34/lib/android.frameworks.cameraservice.common-V1-ndk.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.frameworks.cameraservice.common-V1-ndk.so \
    $(LOCAL_PATH)/vndk-34/lib/libutilscallstack.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libutilscallstack.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hardware.media.omx@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hardware.media.omx@1.0.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hardware.common-V2-ndk.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hardware.common-V2-ndk.so \
    $(LOCAL_PATH)/vndk-34/lib/libldacBT_enc.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libldacBT_enc.so \
    $(LOCAL_PATH)/vndk-34/lib/libunwindstack.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/libunwindstack.so \
    $(LOCAL_PATH)/vndk-34/lib/android.hidl.memory.token@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/android.hidl.memory.token@1.0.so \
    $(LOCAL_PATH)/vndk-34/lib/hw/android.hidl.memory@1.0-impl.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vndk-34/hw
