default_containers: "product"
default_containers: "system"
default_containers: "system_ext"
default_containers: "vendor"

release_config {
  flag_value_files: "flag_values/ap4a/RELEASE_AVF_ENABLE_EARLY_VM.textproto"
  name: "ap4a"
  flag_value_files: "flag_values/ap4a/RELEASE_TARGET_JAVA_21.textproto"
  flag_value_files: "flag_values/ap4a/RELEASE_KOTLIN_LANG_VERSION.textproto"
}
