import os
import zipfile

def extract_and_generate(apk_path, app_name, output_dir, mk_file):
    print(f"Processing {app_name} from {apk_path}...")
    
    # Target directory to extract to
    extract_target_dir = os.path.join(output_dir, app_name, "lib", "arm64")
    os.makedirs(extract_target_dir, exist_ok=True)
    
    copy_rules = []
    
    with zipfile.ZipFile(apk_path, 'r') as zf:
        for file_info in zf.infolist():
            if file_info.filename.startswith("lib/arm64-v8a/") and file_info.filename.endswith(".so"):
                so_filename = os.path.basename(file_info.filename)
                target_file_path = os.path.join(extract_target_dir, so_filename)
                
                print(f"  Extracting {file_info.filename} -> {target_file_path}")
                # Read and write the library file
                with zf.open(file_info.filename) as src, open(target_file_path, 'wb') as dest:
                    dest.write(src.read())
                
                # Source path relative to device tree root (which is device/lenovo/tb351fu)
                # Let's use relative path in $(DEVICE_PATH)
                src_rel_path = f"$(DEVICE_PATH)/prebuilt/apps/{app_name}/lib/arm64/{so_filename}"
                dest_path = f"$(TARGET_COPY_OUT_PRODUCT)/app/{app_name}/lib/arm64/{so_filename}"
                copy_rules.append(f"PRODUCT_COPY_FILES += {src_rel_path}:{dest_path}")
                
    return copy_rules

def main():
    base_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)))
    nebo_apk = os.path.join(base_dir, "MyScript_Nebo", "MyScript_Nebo.apk")
    calc_apk = os.path.join(base_dir, "MyScript_Calculator", "MyScript_Calculator.apk")
    
    mk_content = [
        "# Auto-generated JNI prebuilt libraries copy rules",
        "# Generated by extract_jni.py",
        ""
    ]
    
    nebo_rules = extract_and_generate(nebo_apk, "MyScript_Nebo", base_dir, None)
    calc_rules = extract_and_generate(calc_apk, "MyScript_Calculator", base_dir, None)
    
    mk_content.extend(nebo_rules)
    mk_content.append("")
    mk_content.extend(calc_rules)
    mk_content.append("")
    
    mk_path = os.path.join(base_dir, "prebuilt_libs.mk")
    with open(mk_path, 'w') as f:
        f.write("\n".join(mk_content))
    print(f"Successfully generated {mk_path}")

if __name__ == "__main__":
    main()
