# Auto-generated JNI prebuilt libraries copy rules
# Generated by extract_jni.py

PRODUCT_COPY_FILES += $(DEVICE_PATH)/prebuilt/apps/MyScript_Nebo/lib/arm64/libMyScript2D.so:$(TARGET_COPY_OUT_PRODUCT)/app/MyScript_Nebo/lib/arm64/libMyScript2D.so
PRODUCT_COPY_FILES += $(DEVICE_PATH)/prebuilt/apps/MyScript_Nebo/lib/arm64/libMyScriptAnalyzer.so:$(TARGET_COPY_OUT_PRODUCT)/app/MyScript_Nebo/lib/arm64/libMyScriptAnalyzer.so
PRODUCT_COPY_FILES += $(DEVICE_PATH)/prebuilt/apps/MyScript_Nebo/lib/arm64/libMyScriptDocument.so:$(TARGET_COPY_OUT_PRODUCT)/app/MyScript_Nebo/lib/arm64/libMyScriptDocument.so
PRODUCT_COPY_FILES += $(DEVICE_PATH)/prebuilt/apps/MyScript_Nebo/lib/arm64/libMyScriptEngine.so:$(TARGET_COPY_OUT_PRODUCT)/app/MyScript_Nebo/lib/arm64/libMyScriptEngine.so
PRODUCT_COPY_FILES += $(DEVICE_PATH)/prebuilt/apps/MyScript_Nebo/lib/arm64/libMyScriptGesture.so:$(TARGET_COPY_OUT_PRODUCT)/app/MyScript_Nebo/lib/arm64/libMyScriptGesture.so
PRODUCT_COPY_FILES += $(DEVICE_PATH)/prebuilt/apps/MyScript_Nebo/lib/arm64/libMyScriptInk.so:$(TARGET_COPY_OUT_PRODUCT)/app/MyScript_Nebo/lib/arm64/libMyScriptInk.so
PRODUCT_COPY_FILES += $(DEVICE_PATH)/prebuilt/apps/MyScript_Nebo/lib/arm64/libMyScriptMath.so:$(TARGET_COPY_OUT_PRODUCT)/app/MyScript_Nebo/lib/arm64/libMyScriptMath.so
PRODUCT_COPY_FILES += $(DEVICE_PATH)/prebuilt/apps/MyScript_Nebo/lib/arm64/libMyScriptPrediction.so:$(TARGET_COPY_OUT_PRODUCT)/app/MyScript_Nebo/lib/arm64/libMyScriptPrediction.so
PRODUCT_COPY_FILES += $(DEVICE_PATH)/prebuilt/apps/MyScript_Nebo/lib/arm64/libMyScriptShape.so:$(TARGET_COPY_OUT_PRODUCT)/app/MyScript_Nebo/lib/arm64/libMyScriptShape.so
PRODUCT_COPY_FILES += $(DEVICE_PATH)/prebuilt/apps/MyScript_Nebo/lib/arm64/libMyScriptText.so:$(TARGET_COPY_OUT_PRODUCT)/app/MyScript_Nebo/lib/arm64/libMyScriptText.so
PRODUCT_COPY_FILES += $(DEVICE_PATH)/prebuilt/apps/MyScript_Nebo/lib/arm64/libNebo.so:$(TARGET_COPY_OUT_PRODUCT)/app/MyScript_Nebo/lib/arm64/libNebo.so
PRODUCT_COPY_FILES += $(DEVICE_PATH)/prebuilt/apps/MyScript_Nebo/lib/arm64/libPDFNetC.so:$(TARGET_COPY_OUT_PRODUCT)/app/MyScript_Nebo/lib/arm64/libPDFNetC.so
PRODUCT_COPY_FILES += $(DEVICE_PATH)/prebuilt/apps/MyScript_Nebo/lib/arm64/libandroidx.graphics.path.so:$(TARGET_COPY_OUT_PRODUCT)/app/MyScript_Nebo/lib/arm64/libandroidx.graphics.path.so
PRODUCT_COPY_FILES += $(DEVICE_PATH)/prebuilt/apps/MyScript_Nebo/lib/arm64/libc++_shared.so:$(TARGET_COPY_OUT_PRODUCT)/app/MyScript_Nebo/lib/arm64/libc++_shared.so
PRODUCT_COPY_FILES += $(DEVICE_PATH)/prebuilt/apps/MyScript_Nebo/lib/arm64/libdatastore_shared_counter.so:$(TARGET_COPY_OUT_PRODUCT)/app/MyScript_Nebo/lib/arm64/libdatastore_shared_counter.so

PRODUCT_COPY_FILES += $(DEVICE_PATH)/prebuilt/apps/MyScript_Calculator/lib/arm64/libMyScript2D.so:$(TARGET_COPY_OUT_PRODUCT)/app/MyScript_Calculator/lib/arm64/libMyScript2D.so
PRODUCT_COPY_FILES += $(DEVICE_PATH)/prebuilt/apps/MyScript_Calculator/lib/arm64/libMyScriptDocument.so:$(TARGET_COPY_OUT_PRODUCT)/app/MyScript_Calculator/lib/arm64/libMyScriptDocument.so
PRODUCT_COPY_FILES += $(DEVICE_PATH)/prebuilt/apps/MyScript_Calculator/lib/arm64/libMyScriptEngine.so:$(TARGET_COPY_OUT_PRODUCT)/app/MyScript_Calculator/lib/arm64/libMyScriptEngine.so
PRODUCT_COPY_FILES += $(DEVICE_PATH)/prebuilt/apps/MyScript_Calculator/lib/arm64/libMyScriptGesture.so:$(TARGET_COPY_OUT_PRODUCT)/app/MyScript_Calculator/lib/arm64/libMyScriptGesture.so
PRODUCT_COPY_FILES += $(DEVICE_PATH)/prebuilt/apps/MyScript_Calculator/lib/arm64/libMyScriptInk.so:$(TARGET_COPY_OUT_PRODUCT)/app/MyScript_Calculator/lib/arm64/libMyScriptInk.so
PRODUCT_COPY_FILES += $(DEVICE_PATH)/prebuilt/apps/MyScript_Calculator/lib/arm64/libMyScriptMath.so:$(TARGET_COPY_OUT_PRODUCT)/app/MyScript_Calculator/lib/arm64/libMyScriptMath.so
PRODUCT_COPY_FILES += $(DEVICE_PATH)/prebuilt/apps/MyScript_Calculator/lib/arm64/libc++_shared.so:$(TARGET_COPY_OUT_PRODUCT)/app/MyScript_Calculator/lib/arm64/libc++_shared.so
PRODUCT_COPY_FILES += $(DEVICE_PATH)/prebuilt/apps/MyScript_Calculator/lib/arm64/libiink.so:$(TARGET_COPY_OUT_PRODUCT)/app/MyScript_Calculator/lib/arm64/libiink.so
